GET http://webarush.arush.local/api/user
Accept: application/json
Authorization: Bearer 19|XgxUbSfQZGEWICjVZwzmTaRzwVzHoPhqs8TiojG7840768cc

### GUARDAR USUARIO
POST http://webarush.arush.local/api/user
Accept: application/json
Content-Type: application/json

{
    "name": "Carlos Rivera Guillen",
    "email": "mail@mail.com",
    "password": "Yseadr2025mil"
}

### ACTUALIZAR USUARIO
PUT http://webarush.arush.local/api/user/5
Accept: application/json
Content-Type: application/json

{
    "name": "Alex Rivera",
    "email": "alex@rivera.com",
    "password": "Yseadr20203f2"
}

### ELIMINAR USUARIO
DELETE http://webarush.arush.local/api/user/4
Accept: application/json
Content-Type: application/json